"""Ajout des clés API Babbar et SerpApi dans Configuration

Revision ID: 07c3fc6e6efa
Revises: 090a6059ae6a
Create Date: 2025-11-12 11:09:38.227891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c3fc6e6efa'
down_revision = '090a6059ae6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('babbar_api_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('serpapi_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_babbar_sync', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.drop_column('last_babbar_sync')
        batch_op.drop_column('serpapi_key')
        batch_op.drop_column('babbar_api_key')

    # ### end Alembic commands ###
