"""Ajout des clés et dates pour SerpApi

Revision ID: 22fa4407803b
Revises: 07c3fc6e6efa
Create Date: 2025-11-12 11:28:32.516384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22fa4407803b'
down_revision = '07c3fc6e6efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_serpapi_sync', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.drop_column('last_serpapi_sync')

    # ### end Alembic commands ###
