"""baseline existing schema

Revision ID: a6ac343b24bf
Revises: 
Create Date: 2025-11-04 14:59:46.261897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ac343b24bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_backlinks', sa.Integer(), nullable=True),
    sa.Column('total_domains', sa.Integer(), nullable=True),
    sa.Column('follow_percentage', sa.Float(), nullable=True),
    sa.Column('avg_quality', sa.Float(), nullable=True),
    sa.Column('links_gained', sa.Integer(), nullable=True),
    sa.Column('links_lost', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website_stats')
    # ### end Alembic commands ###
