"""init postgres

Revision ID: e813fd22bb05
Revises: 
Create Date: 2025-11-17 15:38:39.763337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e813fd22bb05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('babbar_api_key', sa.String(length=255), nullable=True),
    sa.Column('serpapi_key', sa.String(length=255), nullable=True),
    sa.Column('last_babbar_sync', sa.DateTime(), nullable=True),
    sa.Column('last_serpapi_sync', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valeur', sa.String(length=50), nullable=False),
    sa.Column('couleur', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('valeur')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('grantee_id', sa.Integer(), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['grantee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'grantee_id', name='uix_owner_grantee')
    )
    op.create_table('website',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('domains', sa.String(length=250), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('source_plateforme', sa.String(length=100), nullable=True),
    sa.Column('link_to_check', sa.String(length=250), nullable=True),
    sa.Column('anchor_text', sa.String(length=250), nullable=True),
    sa.Column('link_status', sa.String(length=250), nullable=True),
    sa.Column('anchor_status', sa.String(length=250), nullable=True),
    sa.Column('first_checked', sa.DateTime(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('page_value', sa.Integer(), nullable=True),
    sa.Column('page_trust', sa.Integer(), nullable=True),
    sa.Column('bas', sa.Integer(), nullable=True),
    sa.Column('backlinks_external', sa.Integer(), nullable=True),
    sa.Column('num_outlinks_ext', sa.Integer(), nullable=True),
    sa.Column('link_follow_status', sa.String(length=50), nullable=True),
    sa.Column('google_index_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'link_to_check', 'user_id', name='uix_url_linktocheck')
    )
    op.create_table('website_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_backlinks', sa.Integer(), nullable=True),
    sa.Column('total_domains', sa.Integer(), nullable=True),
    sa.Column('follow_percentage', sa.Float(), nullable=True),
    sa.Column('avg_quality', sa.Float(), nullable=True),
    sa.Column('links_gained', sa.Integer(), nullable=True),
    sa.Column('links_lost', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website_stats')
    op.drop_table('website')
    op.drop_table('user_access')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('source')
    op.drop_table('configuration')
    # ### end Alembic commands ###
